name: florescer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  fl_chart: ^0.10.1
  flutter_auth_buttons: ^0.8.0
  font_awesome_flutter: ^8.8.1
  google_sign_in: ^4.5.1
  json_annotation: ^3.0.1
  mask_text_input_formatter: ^1.0.7
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  state_gen:
    git: https://github.com/rodrigoaddor/state_gen.git

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'
