on:
  push:
    tags:
      - '*.*.*'
name: Build Flutter APK
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'beta'
      - name: Build APK
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          # KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          # KEYSTORE: ${{ secrets.KEYSTORE }} 
        # run: |
        #   echo "$KEY_PROPERTIES" | base64 --decode > "android/key.properties"
        #   echo "$KEYSTORE" | base64 --decode > "key.jks"
        run: |
          echo "$GOOGLE_SERVICES" | base64 --decode > "android/app/google-services.json"
          flutter build apk --split-per-abi --build-number ${{ github.run_number }} --build-name ${GITHUB_REF:10}
          cd build/app/outputs/apk/release
          mv app-arm64-v8a-release.apk ${{ github.event.repository.name }}-${GITHUB_REF:10}-arm64-v8a.apk 
          mv app-armeabi-v7a-release.apk ${{ github.event.repository.name }}-${GITHUB_REF:10}-armeabi-v7a.apk 
          mv app-x86_64-release.apk ${{ github.event.repository.name }}-${GITHUB_REF:10}-x86_64.apk
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/release/*.apk'
          token: ${{ github.token }}
      - name: Build Web
        run: |
          flutter config --enable-web
          flutter build web
      - name: Setup Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build/web
